version: '3.8'
services:
 db:
    image: mysql:5.7
    container_name: db_desafiovirtex
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: desafiovirtex
    ports:
      - "3306:3306"
    volumes:
      - db_desafiovirtex:/var/lib/mysql
    restart: unless-stopped

volumes:
 db_desafiovirtex:
